deel_home_task:
  outputs:
    dev:
      account: opb84404.us-east-1
      user: "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      database: deel_dev
      role: sysadmin
      schema: ggalego
      warehouse: compute_wh
      threads: 4
      type: snowflake
    prod:
      account: opb84404.us-east-1
      user: "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      database: deel
      role: sysadmin
      schema: trusted
      warehouse: compute_wh
      threads: 4
      type: snowflake
  target: prod