deel_home_task:
  outputs:
    dev:
      account: DQHJJUG-AWB43339
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: dev_analytics
      role: sysadmin
      schema: ggalego
      warehouse: compute_wh
      threads: 4
      type: snowflake
    prod:
      account: DQHJJUG-AWB43339
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: analytics
      role: sysadmin
      schema: refined
      warehouse: compute_wh
      threads: 4
      type: snowflake
  target: prod